type = "card"
gallery = true
title = "摄影"
description = "我收藏的一组照片，记录光影、色彩与场景。"

[[items]]
title = ""
image = "/photography/1.jpeg"

[[items]]
title = ""
image = "/photography/2.jpeg"

[[items]]
title = ""
image = "/photography/3.jpeg"

[[items]]
title = ""
image = "/photography/4.jpeg"

[[items]]
title = ""
image = "/photography/5.jpeg"

[[items]]
title = ""
image = "/photography/6.jpeg"

[[items]]
title = ""
image = "/photography/7.jpeg"

[[items]]
title = ""
image = "/photography/8.jpeg"

[[items]]
title = ""
image = "/photography/9.jpeg"

[[items]]
title = ""
image = "/photography/10.jpeg"

[[items]]
title = ""
image = "/photography/11.jpeg"

[[items]]
title = ""
image = "/photography/12.jpeg"

[[items]]
title = ""
image = "/photography/13.jpeg"

[[items]]
title = ""
image = "/photography/14.jpeg"

[[items]]
title = ""
image = "/photography/15.jpeg"

[[items]]
title = ""
image = "/photography/16.jpeg"

[[items]]
title = ""
image = "/photography/17.jpeg"

[[items]]
title = ""
image = "/photography/18.jpeg"

[[items]]
title = ""
image = "/photography/19.jpeg"

[[items]]
title = ""
image = "/photography/20.jpeg"

[[items]]
title = ""
image = "/photography/21.jpeg"

[[items]]
title = ""
image = "/photography/22.jpeg"

[[items]]
title = ""
image = "/photography/23.jpeg"

[[items]]
title = ""
image = "/photography/24.jpeg"

[[items]]
title = ""
image = "/photography/25.jpeg"

[[items]]
title = ""
image = "/photography/26.jpeg"

[[items]]
title = ""
image = "/photography/27.jpeg"

[[items]]
title = ""
image = "/photography/28.jpeg"

[[items]]
title = ""
image = "/photography/29.jpeg"

[[items]]
title = ""
image = "/photography/30.jpeg"

[[items]]
title = ""
image = "/photography/31.jpeg"

[[items]]
title = ""
image = "/photography/2AA8857B-9D8D-4B7A-AEF2-A6DF10C068E9_1_105_c.jpeg"

[[items]]
title = ""
image = "/photography/4D3F4058-2F7C-4EB6-8581-5B300F74CC5C_1_201_a.jpeg"

[[items]]
title = ""
image = "/photography/84CE8E29-EA77-4249-BBD0-8A3FD826E74B.jpeg"

[[items]]
title = ""
image = "/photography/8FC10363-EF85-4A84-A804-3A3F3E3D666E_1_105_c.jpeg"

[[items]]
title = ""
image = "/photography/D178EFCE-D146-434E-AE4F-EEA5D9693E9C.jpeg"
